# Generated by Django 5.2 on 2025-04-18 16:32

import content_reader.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Practical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1, unique=True)),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(default="Описание")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Practical_text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=250)),
                ("body", models.TextField()),
                ("download", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["step"],
            },
        ),
        migrations.CreateModel(
            name="Practical_work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField(default=1)),
                ("task", models.TextField(verbose_name="Текст задания")),
                ("hint", models.TextField(blank=True, verbose_name="Подсказка")),
                (
                    "expected_output",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ожидаемый вывод"
                    ),
                ),
            ],
            options={
                "verbose_name": "Практический редактор",
                "verbose_name_plural": "Практические редакторы",
                "ordering": ["step"],
            },
        ),
        migrations.CreateModel(
            name="PracticalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField()),
                (
                    "file",
                    models.FileField(
                        storage=content_reader.models.PracticalFileStorage(),
                        upload_to="practical_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["doc", "docx", "docs", "txt"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
