# Generated by Django 5.2 on 2025-04-18 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content_reader", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="practical",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="practical_text",
            name="practical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_reader.practical",
            ),
        ),
        migrations.AddField(
            model_name="practical_work",
            name="practical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_reader.practical",
            ),
        ),
        migrations.AddField(
            model_name="practicalfile",
            name="practical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_reader.practical",
            ),
        ),
        migrations.AddField(
            model_name="practicalfile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="practical_text",
            constraint=models.UniqueConstraint(
                fields=("practical", "step"), name="unique_step_per_practical"
            ),
        ),
        migrations.AddConstraint(
            model_name="practical_work",
            constraint=models.UniqueConstraint(
                fields=("practical", "step"), name="unique_practical_work_step"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="practicalfile",
            unique_together={("practical", "step", "user")},
        ),
    ]
