# Generated by Django 5.2 on 2025-04-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_reader", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicalfile",
            name="score",
            field=models.IntegerField(
                blank=True, choices=[(2, "2"), (3, "3"), (4, "4"), (5, "5")], null=True
            ),
        ),
    ]
