# Generated by Django 5.2 on 2025-04-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_reader", "0003_practicalfile_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPracticalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "practical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="content_reader.practical",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practical_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по практической работе",
                "verbose_name_plural": "Прогресс по практическим работам",
                "indexes": [
                    models.Index(
                        fields=["user", "practical"],
                        name="content_rea_user_id_68cdd3_idx",
                    ),
                    models.Index(
                        fields=["is_completed"], name="content_rea_is_comp_4f3d48_idx"
                    ),
                    models.Index(
                        fields=["is_started"], name="content_rea_is_star_baa067_idx"
                    ),
                ],
                "unique_together": {("user", "practical")},
            },
        ),
    ]
