# Generated by Django 5.2 on 2025-04-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_reader", "0004_userpracticalprogress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPracticalProgress",
        ),
    ]
