# Generated by Django 5.2 on 2025-05-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_reader", "0005_delete_userpracticalprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicalfile",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
