# Generated by Django 5.2 on 2025-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_reader", "0006_practicalfile_comment"),
        ("learning", "0005_competency_content_competencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="practical",
            name="competencies",
            field=models.ManyToManyField(
                related_name="practicals",
                to="learning.competency",
                verbose_name="Компетенции",
            ),
        ),
    ]
