# Generated by Django 5.2 on 2025-04-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: ОФ-409-079-4-1",
                        max_length=50,
                        unique=True,
                        verbose_name="Название группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Группа студента (если применимо)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="landing.group",
                verbose_name="Группа",
            ),
        ),
    ]
