# Generated by Django 5.2 on 2025-05-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_group_customuser_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=20,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram",
            field=models.CharField(
                blank=True,
                help_text="Telegram username (например, @username)",
                max_length=50,
                null=True,
                verbose_name="Telegram",
            ),
        ),
    ]
