# Generated by Django 5.2 on 2025-04-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercontentprogress",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="usercontentprogress",
            name="started_at",
        ),
    ]
