# Generated by Django 5.2 on 2025-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_remove_usercontentprogress_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("MC", "Выбор ответа"), ("FB", "Дополнение")],
                default="MC",
                max_length=2,
            ),
        ),
    ]
