# Generated by Django 5.2 on 2025-05-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_question_correct_answer_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="matching_answers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MC", "Выбор ответа"),
                    ("FB", "Дополнение"),
                    ("MT", "Соответствие"),
                ],
                default="MC",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("definition", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_pairs",
                        to="learning.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("question", "term")},
            },
        ),
    ]
