# Generated by Django 5.2 on 2025-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_useranswer_matching_answers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Например: ПК 5.1",
                        max_length=20,
                        unique=True,
                        verbose_name="Код компетенции",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название компетенции",
                        max_length=255,
                        verbose_name="Название компетенции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="content",
            name="competencies",
            field=models.ManyToManyField(
                related_name="contents",
                to="learning.competency",
                verbose_name="Компетенции",
            ),
        ),
    ]
